### ISSUE TITLE
Bug of caching

### ISSUE THREAD

**Issue by GVX111** [aspnet/Caching#134]
Error
<pre>   at Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue[TItem](IMemoryCache cache, Object key, TItem& value)
   at Microsoft.Data.Entity.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.CompileQuery[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.Data.Entity.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at Microsoft.Data.Entity.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at ITN.TS.Administrator.Controllers.ContentController.AddContent(Int32 id, Int32 parent, Boolean viewMode) in D:\Givi\ITN.TS.FW\src\ITN.TS.Web\Modules\ITN.TS.Administrator\Controllers\ContentController.cs:line 84.</pre>

**Comment by davidfowl** [comment]
That's not enough information. Try following the bug template https://github.com/aspnet/Home/wiki/Functional-bug-template
