### ISSUE TITLE
sqlservercache command fails to run due to runtime compatibility check

### ISSUE THREAD

**Issue by danroth27** [aspnet/Caching#143]
```
C:\>sqlservercache
System.InvalidOperationException: The current runtime target framework is not compatible with 'app'.
Current runtime target framework: 'DNX,Version=v4.5.1 (dnx451)'
 Version:      1.0.0-rc1-16231
 Type:         Clr
 Architecture: x64
 OS Name:      Windows
 OS Version:   10.0
 Runtime Id:   win10-x64

Please make sure the runtime matches a framework specified in project.json
   at Microsoft.Dnx.ApplicationHost.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

**Comment by danroth27** [comment]
This appears to be because sqlservercache targets net451 and dotnet5.4 instead of dnx451 and dnxcore50.

**Comment by muratg** [comment]
@danroth27 Did you try with RC2?

**Comment by danroth27** [comment]
I tried the rc1 version of the tool with the rc2 dnx. Still doesn't work.

**Comment by muratg** [comment]
I guess once we have the new TFMs and update all our project.json files, we'd be testing this once more.

**Comment by muratg** [comment]
Assigning to @BrennanConroy. Hopefully we'll get the new TFMs in soon.

**Comment by BrennanConroy** [comment]
Since this isn't how commands are run anymore I'm closing this.
I did check if the command could run though and did eadd03f74bb49cc70ba63b685a610e5877b354b9 as a result

**Comment by muratg** [comment]
Sounds good, thanks!

**Comment by murpheux** [comment]
Hi @danroth27 Did you find a fix to this? I am having same issues.

**Comment by muratg** [comment]
@murpheux What's the version of the tool?

**Comment by murpheux** [comment]
I have an ASP.Net project with dnx461 and I am running with dnx 1.0.0-rc1-update2 -arch x64

**Comment by muratg** [comment]
@murpheux DNX was obsolete as of RC2. Now that ASP.NET Core 1.0.0 is released, I recommend moving your project to dotnet CLI/SDK. Follow the links on https://dot.net.
