### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by dewebeloper** [aspnet/Caching#212]
I have this piece of code
```
for (int i = 0; i < recipeints.Count; i++)
						{
							JObject recipient = (JObject)recipeints[i];
							Task.Factory.StartNew(() =>
							{
								string mailBody = render.RenderToString("NewInvoiceNotification", recipient["header"]);
								foreach (string email in recipient["addresses"])
								{
									EMailMessage mail = new EMailMessage(subject, mailBody, email);
									emailService.SendMail(mail);
								}
							});
						}
```

and this is line where I render Razor View to string
`string mailBody = render.RenderToString("NewInvoiceNotification", recipient["header"]);`

RenderToString is

```
public string RenderToString<TModel>(string viewName, TModel model, string viewPath)
	    {
			var engine = _serviceProvider.GetService(typeof(IRazorViewEngine)) as IRazorViewEngine;
			var tempDataProvider = _serviceProvider.GetService(typeof(ITempDataProvider)) as ITempDataProvider;

			if (engine == null)
			{
				throw new Exception("Can't find IRazorViewEngine");
			}

			var actionContext = GetActionContext();

			var viewEngineResult = engine.FindView(actionContext, viewPath, false);

			if (!viewEngineResult.Success)
			{
				throw new InvalidOperationException($"Couldn't find view '{viewName}'");
			}

			var view = viewEngineResult.View;

			var viewData = new ViewDataDictionary<TModel>(metadataProvider: new EmptyModelMetadataProvider(),
				modelState: new ModelStateDictionary())
			{
				Model = model,
			};
			viewData["CurrentRequestSettings"] = _currentRequestSettings;
			viewData["CurrentDomain"] = _curentDomain;
			using (var output = new StringWriter())
			{
				var viewContext = new ViewContext(
					actionContext,
					view,
					viewData,
					new TempDataDictionary(actionContext.HttpContext, tempDataProvider),
					output,
					new HtmlHelperOptions());

				view.RenderAsync(viewContext).GetAwaiter().GetResult();

				return output.ToString();
			}
		}
```

This works sometime ok, sometime not. I can't figure out what is wrong.
I get two type of errors:    Collection was modified; enumeration operation may not execute. and Stack Empty

For Collection was modified; enumeration operation may not execute. I have follow stack:
```
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Microsoft.Extensions.Caching.Memory.CacheEntry.PropageOptions(CacheEntry parent)
   at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value, MemoryCacheEntryOptions options)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.OnCacheMiss(ViewLocationExpanderContext expanderContext, ViewLocationCacheKey cacheKey)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.LocatePageFromViewLocations(ActionContext actionContext, String pageName, Boolean isMainPage)
   at Microsoft.AspNetCore.Mvc.Razor.RazorViewEngine.FindView(ActionContext context, String viewName, Boolean isMainPage)
   at Registrator.Repo.Classess.RenderView.RenderToString[TModel](String viewName, TModel model, String viewPath) in F:\TFSSource\Registrator\Registrator v1.0.1\Data\Registrator.Repo\Classess\RenderView.cs:line 96
   at Registrator.Repo.Classess.RenderView.RenderToString(String viewName, Object model) in F:\TFSSource\Registrator\Registrator v1.0.1\Data\Registrator.Repo\Classess\RenderView.cs:line 68
   at Registrator.Repo.InvoiceRepo.<>c__DisplayClass3_5.<UploadIvoiceFromJson>b__3() in F:\TFSSource\Registrator\Registrator v1.0.1\Data\Registrator.Repo\InvoiceRepo.cs:line 315
   at System.Threading.Tasks.Task.Execute()
```

Stack empty also is related with Microsoft.Extensions.Caching.Memory.
Is this bug or I doing something wrong?

**Comment by davidfowl** [comment]
Is this with the 1.0.0 version of caching?

**Comment by dewebeloper** [comment]
It is. "Microsoft.Extensions.Caching.Memory": "1.0.0-rc2-final"

**Comment by sebastienros** [comment]
rc2 is not 1.0. This was fixed for 1.0 with https://github.com/aspnet/Caching/issues/184

**Comment by dewebeloper** [comment]
When 1.0 will be published?

**Comment by sebastienros** [comment]
Two weeks ago, here is the link on nuget.org: https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/

You should update everything to 1.0 RTM from here https://www.microsoft.com/net

**Comment by dewebeloper** [comment]
Cool. Thanks
