### ISSUE TITLE
Redis SessionMiddleware throw StackExchange.Redis.RedisServerException

### ISSUE THREAD

**Issue by laoshancun** [aspnet/Caching#241]
hi,when i use redis session middleware,i got this.
```
Exception thrown: 'StackExchange.Redis.RedisServerException' in System.Private.CoreLib.ni.dll
Exception thrown: 'StackExchange.Redis.RedisServerException' in System.Private.CoreLib.ni.dll
Exception thrown: 'StackExchange.Redis.RedisServerException' in System.Private.CoreLib.ni.dll
fail: Microsoft.AspNetCore.Session.SessionMiddleware[1]
      Error closing the session.
StackExchange.Redis.RedisServerException: ERR Error compiling script (new function): user_script:1: unexpected symbol near '�' 
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisExtensions.<HashMemberGetAsync>d__2.MoveNext() in e:\dotnetcore\validate\Extensions\RedisExtensions.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<GetAndRefreshAsync>d__19.MoveNext() in e:\dotnetcore\validate\Extensions\RedisCache.cs:line 231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Caching.Redis.RedisCache.<RefreshAsync>d__15.MoveNext() in e:\dotnetcore\validate\Extensions\RedisCache.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.DistributedSession.<CommitAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
```

**Comment by muratg** [comment]
Can you provide a simple app that reproduces this issue, ideally on a GitHub repo?

**Comment by laoshancun** [comment]
quotes error,ignore this
```
private const string HmGetScript = (@"return redis.call(‘HMGET‘, KEYS[1], unpack(ARGV))");
```
this is a mistake, thanks!
