### ISSUE TITLE
There is an exception when I use Wide Area Network IP to connect redis server

### ISSUE THREAD

**Issue by Jamesxql** [aspnet/Caching#279]
I use IDistributedCache interface to set data to a redis server.

and my connection string is like this: 
`54.222.x.x:6379,keepAlive=-1,syncTimeout=1000,allowAdmin=True,connectTimeout=5000,password=123456,writeBuffer=4096,connectRetry=3,abortConnect=False`

The NETCore throw a exception:

```
Unhandled Exception: StackExchange.Redis.RedisConnectionException: No connection is available to service this operation: EVAL ---> StackExchange.Redis.RedisConnectionException: UnableToConnect on 54.222.253.4:6379/Interactive, origin: ResetNonConnected, input-buffer: 0, outstanding: 0, last-read: 5s ago, last-write: 5s ago, unanswered-write: 35393s ago, keep-alive: 60s, pending: 0, state: Connecting, last-heartbeat: never, last-mbeat: -1s ago, global: 5s ago
   --- End of inner exception stack trace ---
   at StackExchange.Redis.ConnectionMultiplexer.ThrowFailed[T](TaskCompletionSource`1 source, Exception unthrownException)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Caching.Redis.RedisCache.<SetAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Home.Program.Main(String[] args) in /home/ubuntu/Home/Home/Program.cs:line 24
```

But if I use a LAN IP, like this: 
`172.169.x.x:6379,keepAlive=-1,syncTimeout=1000,allowAdmin=True,connectTimeout=5000,password=123456,writeBuffer=4096,connectRetry=3,abortConnect=False`

Nothing is wrong.

Why is this error?

**Comment by Jamesxql** [comment]
This exception was thrown if I ran my program on Ubuntu.16.04-x64.

On Windows everything is OK.

**Comment by Tratcher** [comment]
This is a question for StackExchange.Redis, or just general TCP/IP routing, it's unrelated to ASP.NET Caching.

**Comment by Jamesxql** [comment]
Sorry, it's a general TCP/IP routing problem. I have handled it.
