### ISSUE TITLE
Often a timeout

### ISSUE THREAD

**Issue by wanghaoxing** [aspnet/Caching#433]
``` json
Timeout performing EVAL, inst: 5, queue: 1, qu: 0, qs: 1, qc: 0, wr: 0, wq: 0, in: 19, ar: 0, clientName: , serverEndpoint: 172.16.0.146:6379, keyHashSlot: 12452 (Please take a look at this article for some common client-side issues that can cause timeouts: http://stackexchange.github.io/StackExchange.Redis/Timeouts)- at StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:line 2120
at StackExchange.Redis.RedisBase.ExecuteSync[T](Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:line 81
at StackExchange.Redis.RedisDatabase.ScriptEvaluate(String script, RedisKey[] keys, RedisValue[] values, CommandFlags flags) in c:\code\StackExchange.Redis\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:line 1052
at Microsoft.Extensions.Caching.Redis.RedisExtensions.HashMemberGet(IDatabase cache, String key, String[] members)
at Microsoft.Extensions.Caching.Redis.RedisCache.GetAndRefresh(String key, Boolean getData)
at Microsoft.Extensions.Caching.Distributed.DistributedCacheExtensions.GetString(IDistributedCache cache, String key)
```

**Comment by wanghaoxing** [comment]
I don't know if I'm coding it wrong
mycode
``` c#
        private async Task<T> GetOrAddAsync<T>(string key, Func<T> valueFactory, DistributedCacheEntryOptions distributedCacheEntryOptions)
        {
            var valueString =  _cache.GetString(key);
            if (string.IsNullOrWhiteSpace(valueString))
            {
                lock (key)
                {
                    valueString = _cache.GetString(key);
                    if (string.IsNullOrWhiteSpace(valueString))
                    {
                        var value = valueFactory();
                        _cache.SetString(key, JsonConvert.SerializeObject(value), distributedCacheEntryOptions);
                        return value;
                    }
                }
            }
            return NewtonJsonHelper.DeserializeObject<T>(valueString);
        }
```

**Comment by bragma** [comment]
Hi @wanghaoxing 
I am trying to fix the same problem too. I am not sure if the cause of your timeouts are the same as mine, since your exception is a bit less informative than mine (different project settings), but look at this:

https://github.com/StackExchange/StackExchange.Redis/blob/master/docs/Timeouts.md

and this:

https://gist.github.com/JonCole/e65411214030f0d823cb

In a brief, you probably have to fiddle with ThreadPool.SetMinThreads(...)
